---
version: "3"
services:
  fmd2:
    build: ./
    #image: banhcanh/docker-fmd2:kasm-v3
    container_name: fmd2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK=022 #optional
      - THRESHOLD_MINUTES=5
      - TRANSFER_FILE_TYPE=.cbz
    ports:
      - 3000:3000
    volumes:
      - ./tmp/FMD2/userdata:/app/FMD2/userdata
      - ./tmp/downloads:/downloads
    restart: unless-stopped
