#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/config

chown abc:abc /downloads -R
cd /app/FMD2
if [ ! -f '/app/FMD2/userdata/settings.json' ]; then cp /settings.json /FMD2/userdata/settings.json; fi
chown abc:abc /app/FMD2 -R
chown abc:abc /fmd2.sh -R
chmod +x /fmd2.sh

if [ ! -d '/config/.fluxbox' ]; then
  cp /fluxbox /config/.fluxbox -r
fi
chown abc:abc /config/.fluxbox -R
